service: opennet-backend

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  api:
    handler: app/main.handler
    events:
      - http:
          path: /api/{proxy+}
          method: ANY
          cors: true
    timeout: 30
    memorySize: 256

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: python-deps
      description: Python dependencies for opennet
    noDeploy:
      - pytest
      - pytest-cov
      - black
      - flake8 